# Generated by Django 2.0.6 on 2018-06-23 15:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('background', versatileimagefield.fields.VersatileImageField(blank=True, max_length=255, null=True, upload_to='block/')),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('animate', models.CharField(blank=True, choices=[('Bounce', (('bounceIn', 'bounceIn'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'))), ('Fade', (('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInDownBig', 'fadeInDownBig'), ('fadeInLeft', 'fadeInLeft'), ('fadeInLeftBig', 'fadeInLeftBig'), ('fadeInRight', 'fadeInRight'), ('fadeInRightBig', 'fadeInRightBig'), ('fadeInUp', 'fadeInUp'), ('fadeInUpBig', 'fadeInUpBig'))), ('Flip', (('flipInX', 'flipInX'), ('flipInY', 'flipInY'))), ('Lightspeed', (('lightSpeedIn', 'lightSpeedIn'),)), ('Rotate', (('rotateIn', 'rotateIn'), ('rotateInDownLeft', 'rotateInDownLeft'), ('rotateInDownRight', 'rotateInDownRight'), ('rotateInUpLeft', 'rotateInUpLeft'), ('rotateInUpRight', 'rotateInUpRight'))), ('Slide', (('slideInUp', 'slideInUp'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'))), ('Zoom', (('zoomIn', 'zoomIn'), ('zoomInDown', 'zoomInDown'), ('zoomInLeft', 'zoomInLeft'), ('zoomInRight', 'zoomInRight'), ('zoomInUp', 'zoomInUp'))), ('Specials', (('jackInTheBox', 'jackInTheBox'), ('rollIn', 'rollIn')))], default='None', max_length=255, null=True)),
            ],
            options={
                'db_table': 'block',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CaruselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(max_length=255, upload_to='caruselitem/')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('text_color', models.CharField(blank=True, max_length=255, null=True)),
                ('animate', models.CharField(blank=True, choices=[('Bounce', (('bounceIn', 'bounceIn'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'))), ('Fade', (('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInDownBig', 'fadeInDownBig'), ('fadeInLeft', 'fadeInLeft'), ('fadeInLeftBig', 'fadeInLeftBig'), ('fadeInRight', 'fadeInRight'), ('fadeInRightBig', 'fadeInRightBig'), ('fadeInUp', 'fadeInUp'), ('fadeInUpBig', 'fadeInUpBig'))), ('Flip', (('flipInX', 'flipInX'), ('flipInY', 'flipInY'))), ('Lightspeed', (('lightSpeedIn', 'lightSpeedIn'),)), ('Rotate', (('rotateIn', 'rotateIn'), ('rotateInDownLeft', 'rotateInDownLeft'), ('rotateInDownRight', 'rotateInDownRight'), ('rotateInUpLeft', 'rotateInUpLeft'), ('rotateInUpRight', 'rotateInUpRight'))), ('Slide', (('slideInUp', 'slideInUp'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'))), ('Zoom', (('zoomIn', 'zoomIn'), ('zoomInDown', 'zoomInDown'), ('zoomInLeft', 'zoomInLeft'), ('zoomInRight', 'zoomInRight'), ('zoomInUp', 'zoomInUp'))), ('Specials', (('jackInTheBox', 'jackInTheBox'), ('rollIn', 'rollIn')))], default='None', max_length=255, null=True)),
            ],
            options={
                'db_table': 'carusel_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'filter_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FilterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(max_length=255, upload_to='filteritem/')),
                ('text', models.TextField(max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('animate', models.CharField(blank=True, choices=[('Bounce', (('bounceIn', 'bounceIn'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'))), ('Fade', (('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInDownBig', 'fadeInDownBig'), ('fadeInLeft', 'fadeInLeft'), ('fadeInLeftBig', 'fadeInLeftBig'), ('fadeInRight', 'fadeInRight'), ('fadeInRightBig', 'fadeInRightBig'), ('fadeInUp', 'fadeInUp'), ('fadeInUpBig', 'fadeInUpBig'))), ('Flip', (('flipInX', 'flipInX'), ('flipInY', 'flipInY'))), ('Lightspeed', (('lightSpeedIn', 'lightSpeedIn'),)), ('Rotate', (('rotateIn', 'rotateIn'), ('rotateInDownLeft', 'rotateInDownLeft'), ('rotateInDownRight', 'rotateInDownRight'), ('rotateInUpLeft', 'rotateInUpLeft'), ('rotateInUpRight', 'rotateInUpRight'))), ('Slide', (('slideInUp', 'slideInUp'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'))), ('Zoom', (('zoomIn', 'zoomIn'), ('zoomInDown', 'zoomInDown'), ('zoomInLeft', 'zoomInLeft'), ('zoomInRight', 'zoomInRight'), ('zoomInUp', 'zoomInUp'))), ('Specials', (('jackInTheBox', 'jackInTheBox'), ('rollIn', 'rollIn')))], default='None', max_length=255, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='filter_category', to='app.FilterCategory')),
            ],
            options={
                'db_table': 'filter_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'home_page',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MapItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('hint', models.CharField(blank=True, max_length=255, null=True)),
                ('baloon', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'map_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=2048)),
                ('title', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True, null=True)),
                ('view', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('layout', models.IntegerField(blank=True, null=True)),
                ('posmenu', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'page',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('section_type', models.CharField(max_length=255)),
                ('display_title', models.IntegerField(blank=True, null=True)),
                ('pos', models.IntegerField(blank=True, null=True)),
                ('title_animate', models.CharField(blank=True, choices=[('Bounce', (('bounceIn', 'bounceIn'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'))), ('Fade', (('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInDownBig', 'fadeInDownBig'), ('fadeInLeft', 'fadeInLeft'), ('fadeInLeftBig', 'fadeInLeftBig'), ('fadeInRight', 'fadeInRight'), ('fadeInRightBig', 'fadeInRightBig'), ('fadeInUp', 'fadeInUp'), ('fadeInUpBig', 'fadeInUpBig'))), ('Flip', (('flipInX', 'flipInX'), ('flipInY', 'flipInY'))), ('Lightspeed', (('lightSpeedIn', 'lightSpeedIn'),)), ('Rotate', (('rotateIn', 'rotateIn'), ('rotateInDownLeft', 'rotateInDownLeft'), ('rotateInDownRight', 'rotateInDownRight'), ('rotateInUpLeft', 'rotateInUpLeft'), ('rotateInUpRight', 'rotateInUpRight'))), ('Slide', (('slideInUp', 'slideInUp'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'))), ('Zoom', (('zoomIn', 'zoomIn'), ('zoomInDown', 'zoomInDown'), ('zoomInLeft', 'zoomInLeft'), ('zoomInRight', 'zoomInRight'), ('zoomInUp', 'zoomInUp'))), ('Specials', (('jackInTheBox', 'jackInTheBox'), ('rollIn', 'rollIn')))], default='None', max_length=255, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.Page')),
            ],
            options={
                'db_table': 'section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(max_length=255, upload_to='sectionimage/')),
                ('position', models.NullBooleanField()),
                ('animate', models.CharField(choices=[('Bounce', (('bounceIn', 'bounceIn'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'))), ('Fade', (('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInDownBig', 'fadeInDownBig'), ('fadeInLeft', 'fadeInLeft'), ('fadeInLeftBig', 'fadeInLeftBig'), ('fadeInRight', 'fadeInRight'), ('fadeInRightBig', 'fadeInRightBig'), ('fadeInUp', 'fadeInUp'), ('fadeInUpBig', 'fadeInUpBig'))), ('Flip', (('flipInX', 'flipInX'), ('flipInY', 'flipInY'))), ('Lightspeed', (('lightSpeedIn', 'lightSpeedIn'),)), ('Rotate', (('rotateIn', 'rotateIn'), ('rotateInDownLeft', 'rotateInDownLeft'), ('rotateInDownRight', 'rotateInDownRight'), ('rotateInUpLeft', 'rotateInUpLeft'), ('rotateInUpRight', 'rotateInUpRight'))), ('Slide', (('slideInUp', 'slideInUp'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'))), ('Zoom', (('zoomIn', 'zoomIn'), ('zoomInDown', 'zoomInDown'), ('zoomInLeft', 'zoomInLeft'), ('zoomInRight', 'zoomInRight'), ('zoomInUp', 'zoomInUp'))), ('Specials', (('jackInTheBox', 'jackInTheBox'), ('rollIn', 'rollIn')))], max_length=255, null=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app.Section')),
            ],
            options={
                'db_table': 'section_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('animate', models.CharField(blank=True, choices=[('Bounce', (('bounceIn', 'bounceIn'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'))), ('Fade', (('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInDownBig', 'fadeInDownBig'), ('fadeInLeft', 'fadeInLeft'), ('fadeInLeftBig', 'fadeInLeftBig'), ('fadeInRight', 'fadeInRight'), ('fadeInRightBig', 'fadeInRightBig'), ('fadeInUp', 'fadeInUp'), ('fadeInUpBig', 'fadeInUpBig'))), ('Flip', (('flipInX', 'flipInX'), ('flipInY', 'flipInY'))), ('Lightspeed', (('lightSpeedIn', 'lightSpeedIn'),)), ('Rotate', (('rotateIn', 'rotateIn'), ('rotateInDownLeft', 'rotateInDownLeft'), ('rotateInDownRight', 'rotateInDownRight'), ('rotateInUpLeft', 'rotateInUpLeft'), ('rotateInUpRight', 'rotateInUpRight'))), ('Slide', (('slideInUp', 'slideInUp'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'))), ('Zoom', (('zoomIn', 'zoomIn'), ('zoomInDown', 'zoomInDown'), ('zoomInLeft', 'zoomInLeft'), ('zoomInRight', 'zoomInRight'), ('zoomInUp', 'zoomInUp'))), ('Specials', (('jackInTheBox', 'jackInTheBox'), ('rollIn', 'rollIn')))], default='None', max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='app.Section')),
            ],
            options={
                'db_table': 'table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_items', to='app.Table')),
            ],
            options={
                'db_table': 'table_item',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='mapitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='app.Section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Page'),
        ),
        migrations.AddField(
            model_name='filteritem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='app.Section'),
        ),
        migrations.AddField(
            model_name='caruselitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carusel', to='app.Section'),
        ),
        migrations.AddField(
            model_name='block',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='app.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='tableitem',
            unique_together={('row', 'col', 'table')},
        ),
    ]
