# Generated by Django 2.0.6 on 2018-06-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180625_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapitem',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
