# Generated by Django 2.0.6 on 2018-06-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180625_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(max_length=255, upload_to='feedback/')),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='mapitem',
            name='section',
        ),
        migrations.AddField(
            model_name='mapitem',
            name='section',
            field=models.ManyToManyField(related_name='map', to='app.Section'),
        ),
    ]
