# Generated by Django 2.0.6 on 2018-06-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180625_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filteritem',
            options={'managed': True, 'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'managed': True, 'ordering': ['posmenu']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'managed': True, 'ordering': ['pos']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'managed': True, 'ordering': ['position']},
        ),
        # migrations.AddField(
            # model_name='feedback',
            # name='created_at',
            # field=models.DateTimeField(auto_now_add=True, default=3),
            # preserve_default=False,
        # ),
        # migrations.AddField(
            # model_name='feedback',
            # name='updated_at',
            # field=models.DateTimeField(auto_now=True),
        # ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='feedback/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homePage', to='app.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='layout',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='view',
            field=models.CharField(blank=True, choices=[('new.html', 'new.html'), ('new1.html', 'new1.html'), ('WebPage1.html', 'WebPage1.html'), ('WebPage2.html', 'WebPage2.html')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='display_title',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('block', 'block'), ('carusel', 'carusel'), ('table', 'table'), ('filter', 'filter'), ('map', 'map')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='position',
            field=models.BooleanField(),
        ),
    ]
