# Generated by Django 2.0.6 on 2018-06-27 17:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180626_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'managed': True, 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='caruselitem',
            options={'managed': True, 'verbose_name': 'Элемент карусели', 'verbose_name_plural': 'Элементы карусели'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True, 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='filtercategory',
            options={'managed': True, 'verbose_name': 'Категория фильтра', 'verbose_name_plural': 'Категории фильтра'},
        ),
        migrations.AlterModelOptions(
            name='filteritem',
            options={'managed': True, 'ordering': ['pos'], 'verbose_name': 'Элемент фильтра', 'verbose_name_plural': 'Элементы фильтра'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'managed': True, 'verbose_name': 'Домашняя страница', 'verbose_name_plural': 'Домашние страницы'},
        ),
        migrations.AlterModelOptions(
            name='mapitem',
            options={'managed': True, 'verbose_name': 'Элемент карты', 'verbose_name_plural': 'Элементы карты'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'managed': True, 'ordering': ['posmenu'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'managed': True, 'ordering': ['pos'], 'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AlterModelOptions(
            name='sectionimage',
            options={'managed': True, 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'managed': True, 'ordering': ['pos'], 'verbose_name': 'Таблица', 'verbose_name_plural': 'Таблицы'},
        ),
        migrations.AlterModelOptions(
            name='tableitem',
            options={'managed': True, 'verbose_name': 'Элемент таблицы', 'verbose_name_plural': 'Элементы таблицы'},
        ),
        migrations.RemoveField(
            model_name='caruselitem',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='filteritem',
            name='position',
        ),
        migrations.RemoveField(
            model_name='table',
            name='position',
        ),
        migrations.AddField(
            model_name='filteritem',
            name='pos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='table',
            name='pos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='block',
            name='animate',
            field=models.CharField(blank=True, choices=[('Bounce', (('bounceIn', 'bounceIn'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'))), ('Fade', (('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInDownBig', 'fadeInDownBig'), ('fadeInLeft', 'fadeInLeft'), ('fadeInLeftBig', 'fadeInLeftBig'), ('fadeInRight', 'fadeInRight'), ('fadeInRightBig', 'fadeInRightBig'), ('fadeInUp', 'fadeInUp'), ('fadeInUpBig', 'fadeInUpBig'))), ('Flip', (('flipInX', 'flipInX'), ('flipInY', 'flipInY'))), ('Lightspeed', (('lightSpeedIn', 'lightSpeedIn'),)), ('Rotate', (('rotateIn', 'rotateIn'), ('rotateInDownLeft', 'rotateInDownLeft'), ('rotateInDownRight', 'rotateInDownRight'), ('rotateInUpLeft', 'rotateInUpLeft'), ('rotateInUpRight', 'rotateInUpRight'))), ('Slide', (('slideInUp', 'slideInUp'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'))), ('Zoom', (('zoomIn', 'zoomIn'), ('zoomInDown', 'zoomInDown'), ('zoomInLeft', 'zoomInLeft'), ('zoomInRight', 'zoomInRight'), ('zoomInUp', 'zoomInUp'))), ('Specials', (('jackInTheBox', 'jackInTheBox'), ('rollIn', 'rollIn')))], default='None', max_length=255, null=True, verbose_name='Анимация'),
        ),
        migrations.AlterField(
            model_name='block',
            name='background',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=255, null=True, upload_to='block/', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='block',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='block',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='block',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='app.Section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='block',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='caruselitem',
            name='animate',
            field=models.CharField(blank=True, choices=[('Bounce', (('bounceIn', 'bounceIn'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'))), ('Fade', (('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInDownBig', 'fadeInDownBig'), ('fadeInLeft', 'fadeInLeft'), ('fadeInLeftBig', 'fadeInLeftBig'), ('fadeInRight', 'fadeInRight'), ('fadeInRightBig', 'fadeInRightBig'), ('fadeInUp', 'fadeInUp'), ('fadeInUpBig', 'fadeInUpBig'))), ('Flip', (('flipInX', 'flipInX'), ('flipInY', 'flipInY'))), ('Lightspeed', (('lightSpeedIn', 'lightSpeedIn'),)), ('Rotate', (('rotateIn', 'rotateIn'), ('rotateInDownLeft', 'rotateInDownLeft'), ('rotateInDownRight', 'rotateInDownRight'), ('rotateInUpLeft', 'rotateInUpLeft'), ('rotateInUpRight', 'rotateInUpRight'))), ('Slide', (('slideInUp', 'slideInUp'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'))), ('Zoom', (('zoomIn', 'zoomIn'), ('zoomInDown', 'zoomInDown'), ('zoomInLeft', 'zoomInLeft'), ('zoomInRight', 'zoomInRight'), ('zoomInUp', 'zoomInUp'))), ('Specials', (('jackInTheBox', 'jackInTheBox'), ('rollIn', 'rollIn')))], default='None', max_length=255, null=True, verbose_name='Анимация'),
        ),
        migrations.AlterField(
            model_name='caruselitem',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='caruselitem',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Url кнопки'),
        ),
        migrations.AlterField(
            model_name='caruselitem',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(max_length=255, upload_to='caruselitem/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='caruselitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carusel', to='app.Section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='caruselitem',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='feedback/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='filtercategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='animate',
            field=models.CharField(blank=True, choices=[('Bounce', (('bounceIn', 'bounceIn'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'))), ('Fade', (('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInDownBig', 'fadeInDownBig'), ('fadeInLeft', 'fadeInLeft'), ('fadeInLeftBig', 'fadeInLeftBig'), ('fadeInRight', 'fadeInRight'), ('fadeInRightBig', 'fadeInRightBig'), ('fadeInUp', 'fadeInUp'), ('fadeInUpBig', 'fadeInUpBig'))), ('Flip', (('flipInX', 'flipInX'), ('flipInY', 'flipInY'))), ('Lightspeed', (('lightSpeedIn', 'lightSpeedIn'),)), ('Rotate', (('rotateIn', 'rotateIn'), ('rotateInDownLeft', 'rotateInDownLeft'), ('rotateInDownRight', 'rotateInDownRight'), ('rotateInUpLeft', 'rotateInUpLeft'), ('rotateInUpRight', 'rotateInUpRight'))), ('Slide', (('slideInUp', 'slideInUp'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'))), ('Zoom', (('zoomIn', 'zoomIn'), ('zoomInDown', 'zoomInDown'), ('zoomInLeft', 'zoomInLeft'), ('zoomInRight', 'zoomInRight'), ('zoomInUp', 'zoomInUp'))), ('Specials', (('jackInTheBox', 'jackInTheBox'), ('rollIn', 'rollIn')))], default='None', max_length=255, null=True, verbose_name='Анимация'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Url кнопки'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='filter_category', to='app.FilterCategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(max_length=255, upload_to='filteritem/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='app.Section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='text',
            field=models.TextField(max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='baloon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Балун'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хинт'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='object',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='section',
            field=models.ManyToManyField(related_name='map', to='app.Section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='page',
            name='layout',
            field=models.BooleanField(verbose_name='Использовать шаблон'),
        ),
        migrations.AlterField(
            model_name='page',
            name='posmenu',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Позиция в меню'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='ЧПУ'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.BooleanField(verbose_name='Отображать'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='page',
            name='view',
            field=models.CharField(blank=True, choices=[('new.html', 'new.html'), ('new1.html', 'new1.html'), ('WebPage1.html', 'WebPage1.html'), ('WebPage2.html', 'WebPage2.html')], max_length=255, null=True, verbose_name='Файл отображения'),
        ),
        migrations.AlterField(
            model_name='section',
            name='display_title',
            field=models.BooleanField(verbose_name='Показывать название'),
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.Page', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='section',
            name='pos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('block', 'block'), ('carusel', 'carusel'), ('table', 'table'), ('filter', 'filter'), ('map', 'map')], max_length=255, verbose_name='Тип секции'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='ЧПУ'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_animate',
            field=models.CharField(blank=True, choices=[('Bounce', (('bounceIn', 'bounceIn'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'))), ('Fade', (('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInDownBig', 'fadeInDownBig'), ('fadeInLeft', 'fadeInLeft'), ('fadeInLeftBig', 'fadeInLeftBig'), ('fadeInRight', 'fadeInRight'), ('fadeInRightBig', 'fadeInRightBig'), ('fadeInUp', 'fadeInUp'), ('fadeInUpBig', 'fadeInUpBig'))), ('Flip', (('flipInX', 'flipInX'), ('flipInY', 'flipInY'))), ('Lightspeed', (('lightSpeedIn', 'lightSpeedIn'),)), ('Rotate', (('rotateIn', 'rotateIn'), ('rotateInDownLeft', 'rotateInDownLeft'), ('rotateInDownRight', 'rotateInDownRight'), ('rotateInUpLeft', 'rotateInUpLeft'), ('rotateInUpRight', 'rotateInUpRight'))), ('Slide', (('slideInUp', 'slideInUp'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'))), ('Zoom', (('zoomIn', 'zoomIn'), ('zoomInDown', 'zoomInDown'), ('zoomInLeft', 'zoomInLeft'), ('zoomInRight', 'zoomInRight'), ('zoomInUp', 'zoomInUp'))), ('Specials', (('jackInTheBox', 'jackInTheBox'), ('rollIn', 'rollIn')))], default='None', max_length=255, null=True, verbose_name='Анимация заголовка'),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='animate',
            field=models.CharField(choices=[('Bounce', (('bounceIn', 'bounceIn'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'))), ('Fade', (('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInDownBig', 'fadeInDownBig'), ('fadeInLeft', 'fadeInLeft'), ('fadeInLeftBig', 'fadeInLeftBig'), ('fadeInRight', 'fadeInRight'), ('fadeInRightBig', 'fadeInRightBig'), ('fadeInUp', 'fadeInUp'), ('fadeInUpBig', 'fadeInUpBig'))), ('Flip', (('flipInX', 'flipInX'), ('flipInY', 'flipInY'))), ('Lightspeed', (('lightSpeedIn', 'lightSpeedIn'),)), ('Rotate', (('rotateIn', 'rotateIn'), ('rotateInDownLeft', 'rotateInDownLeft'), ('rotateInDownRight', 'rotateInDownRight'), ('rotateInUpLeft', 'rotateInUpLeft'), ('rotateInUpRight', 'rotateInUpRight'))), ('Slide', (('slideInUp', 'slideInUp'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'))), ('Zoom', (('zoomIn', 'zoomIn'), ('zoomInDown', 'zoomInDown'), ('zoomInLeft', 'zoomInLeft'), ('zoomInRight', 'zoomInRight'), ('zoomInUp', 'zoomInUp'))), ('Specials', (('jackInTheBox', 'jackInTheBox'), ('rollIn', 'rollIn')))], max_length=255, null=True, verbose_name='Анимация'),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(max_length=255, upload_to='sectionimage/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='position',
            field=models.BooleanField(verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app.Section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='table',
            name='animate',
            field=models.CharField(blank=True, choices=[('Bounce', (('bounceIn', 'bounceIn'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'))), ('Fade', (('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInDownBig', 'fadeInDownBig'), ('fadeInLeft', 'fadeInLeft'), ('fadeInLeftBig', 'fadeInLeftBig'), ('fadeInRight', 'fadeInRight'), ('fadeInRightBig', 'fadeInRightBig'), ('fadeInUp', 'fadeInUp'), ('fadeInUpBig', 'fadeInUpBig'))), ('Flip', (('flipInX', 'flipInX'), ('flipInY', 'flipInY'))), ('Lightspeed', (('lightSpeedIn', 'lightSpeedIn'),)), ('Rotate', (('rotateIn', 'rotateIn'), ('rotateInDownLeft', 'rotateInDownLeft'), ('rotateInDownRight', 'rotateInDownRight'), ('rotateInUpLeft', 'rotateInUpLeft'), ('rotateInUpRight', 'rotateInUpRight'))), ('Slide', (('slideInUp', 'slideInUp'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'))), ('Zoom', (('zoomIn', 'zoomIn'), ('zoomInDown', 'zoomInDown'), ('zoomInLeft', 'zoomInLeft'), ('zoomInRight', 'zoomInRight'), ('zoomInUp', 'zoomInUp'))), ('Specials', (('jackInTheBox', 'jackInTheBox'), ('rollIn', 'rollIn')))], default='None', max_length=255, null=True, verbose_name='Анимация'),
        ),
        migrations.AlterField(
            model_name='table',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='app.Section', verbose_name='секция'),
        ),
        migrations.AlterField(
            model_name='table',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tableitem',
            name='col',
            field=models.IntegerField(verbose_name='Столбец'),
        ),
        migrations.AlterField(
            model_name='tableitem',
            name='row',
            field=models.IntegerField(verbose_name='Строка'),
        ),
        migrations.AlterField(
            model_name='tableitem',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_items', to='app.Table', verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='tableitem',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение'),
        ),
    ]
